# Pull base image.
FROM ubuntu:14.04
MAINTAINER Anand <a3anand@cs.ucsd.edu>

# Install Java.
RUN \
  apt-get update && \
  apt-get install -y openjdk-7-jdk && \
  rm -rf /var/lib/apt/lists/*


# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-7-openjdk-amd64

# Define default command.

COPY *.java /opt/
COPY *.jar /opt/